### ISSUE TITLE
[windows][virtualization] Install Fedora with WSL

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#1137]
Export a Fedora container and then import it into WSL 2.

https://dev.to/bowmanjd/install-fedora-on-windows-subsystem-for-linux-wsl-4b26

**Comment by GuestSneezeOSDev** [comment]
Isn't Fedora 37 EOL?

**Comment by LukeShortCloud** [comment]
Yes, you are correct. The same steps can be used for any version of Fedora. I will be testing and adding notes with how to do this with Fedora 40 specifically. Since Fedora is not officially provided by Microsoft from WSL, I wanted to document this in Root Pages.

**Comment by LukeShortCloud** [comment]
Notes added here: https://rootpages.lukeshort.cloud/latest/windows/virtualization.html#fedora

**Comment by GuestSneezeOSDev** [comment]
alr thanks
