### ISSUE TITLE
[virtualization][kubernetes_administration] Install MetalLB load balancer

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#391]
https://opensource.com/article/20/7/homelab-metallb
https://metallb.universe.tf/installation/

**Comment by ekultails** [comment]
Kubernetes does not provide a Service LoadBalancer back-end by default.

**Comment by ekultails** [comment]
MetalLB is the only load balancer for baremetal. All other load balancers are for public cloud providers. Load balancers for public clouds are normally developed by and automatically deployed by the cloud provider.

https://rancher.com/load-balancing-in-kubernetes

**Comment by ekultails** [comment]
Other baremetal load balancers:

1. Seesaw = Made by Google. Does not ship binaries.

https://linuxhint.com/install_seesaw_ubuntu/
https://opensource.google/projects/seesaw

2. kube-vip

https://github.com/plunder-app/kube-vip
