### ISSUE TITLE
[virtualization][kubernetes_development] Add Carvel notes

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#410]
Carvel used to be called `k14s` and `Kubernetes Tools`.

https://tanzu.vmware.com/content/blog/introducing-k14s-kubernetes-tools-simple-and-composable-tools-for-application-deployment

vendir, ytt, and kapp are the most popular tools that are part of Carvel.

**Comment by ekultails** [comment]
For `ytt`, process a Helm chart template first with `helm tempate` and then use `ytt` for adding overlays.

**Comment by ekultails** [comment]
Delete a kapp application AND the PVCs:

```
$ kapp delete -a <APP> --apply-ignored -y
```

https://carvel.dev/kapp/docs/latest/faq/#why-does-kapp-hang-when-trying-to-delete-a-resource

**Comment by ekultails** [comment]
ytt notes:

- Comments start with `#!`.

**Comment by ekultails** [comment]
The templating language is [starlark-go](https://github.com/google/starlark-go/blob/master/doc/spec.md).
