### ISSUE TITLE
[computer_hardware][laptops] Extend battery life

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#427]
Install and run the services: TLP and auto-cpufreq.

https://github.com/linrunner/TLP
https://github.com/AdnanHodzic/auto-cpufreq

**Comment by ekultails** [comment]
Arch Linux:

```
$ sudo pacman -S auto-cpufreq tlp
$ sudo systemctl enable --now auto-cpufreq tlp
```

These services provide battery life compare to when using Windows. Without these services, Linux battery life can be cut in half or more.
