### ISSUE TITLE
[virtualization][kubernetes_administration] Update TKGm notes from 1.1 to 1.3

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#428]
The `tkg` binary was replaced by the new `tanzu` binary.

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-install-cli.html

**Comment by ekultails** [comment]
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-mgmt-clusters-deploy-management-clusters.html

**Comment by ekultails** [comment]
Pre-reqs for AWS require that an Access key and secret are provided. Generate this by going to:

aws.amazon.com > (select your username in the top-right) > My Security Credentials > Access keys for CLI, SDK, & API access > Create access key > Download .csv file > Close

Also ensure an SSH key pair is configured in the correct EC2 region:

aws.amazon.com > Services > Compute > EC2 > Network & Security > Key Pairs > Create key pair > Create key pair

**Comment by ekultails** [comment]
Delete management cluster: `tanzu management-cluster delete`

**Comment by ekultails** [comment]
`tanzu-core-<OS>_<ARCH>` == `tanzu`
