### ISSUE TITLE
[virtualization][kubernetes_development] Install TKG extensions

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#462]
These will work on any TKG* platform (TKGm, TKGS, and TKGI).

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-extensions-index.html#unpack-bundle

**Comment by ekultails** [comment]
List of TKG Extensions:

- Contour = Ingress
- External DNS = Service Discovery
- Fluent Bit = Log Forwarding
- Harbor = Container Registry
- Monitoring = Prometheus and Grafana

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.3/vmware-tanzu-kubernetes-grid-13/GUID-extensions-index.html
